[package]
name = "rust-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.179.0"
deno_runtime = "0.105.0"
tokio = { version = "1.25.0", features = ["full"] }
url = "2.3.1"
juniper = "0.15.11"
chrono = { version = "0.4.24", features = ["serde"] }
juniper_subscriptions = "0.16.0"
futures = "0.3.28"

actix-web = "4.0.0-beta.9"
actix-rt = "2.2.0"
juniper_actix = "0.4.0"
env_logger = "0.10.0"
serde_json = "1.0.95"
actix = "0.13.0"
uuid = "1.3.0"
log = "0.4.17"
serde = "1.0.159"
secp256k1 = { version = "0.27.0", features = ["rand", "serde"] }
crypto_box = "0.8.2"
lazy_static = "1.4.0"
hex = "0.4.3"
argon2 = { version = "0.5.0", features = ["simple"] }
rand = "0.8.5"
base64 = "0.21.0"
clap = { version = "4.0.8", features = ["derive"] }
fs_extra = "1.3.0"
did-key = "0.2.1"
