[package]
name = "rust-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.179.0"
deno_runtime = "0.105.0"
tokio = { version = "1.25.0", features = ["full"] }
url = "2.3.1"
juniper = "0.15.11"
chrono = "0.4.24"
juniper_subscriptions = "0.16.0"
futures = "0.3.28"
