# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        platform: [macos-10.15, ubuntu-18.04]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v9
      with:
        name: perspect3vism
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g npm
    - run: npm i
    - run: npm run build --if-present
    - run: npm test

  test-windows:
    name: Windows Test
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
      - name: Cache cargo
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo
      - run: $env:path
      - name: Choco install swipl-prolog
        run: choco install swi-prolog
      - run: $env:path += ";C:\Program Files\swipl\bin"
      - run: refreshenv
      - run: $env:path
      - run: Get-Command swipl
      - name: Build Holochain
        env:
          SQLCIPHER_STATIC: 1
        run: |
          rustup target add wasm32-unknown-unknown
          (cargo install lair_keystore --version 0.0.9 || true)
          (cargo install --locked holochain --git https://github.com/holochain/holochain.git --tag holochain-0.0.127 || true)
          (cargo install holochain_cli --version 0.0.28 || true)
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: $env:path
      - run: refreshenv
      - run: $env:path
      - run: npm install -g npm
      - run: npm i
      - run: npm run build --if-present
      - run: npm run test:windows